services:

    announcement_command:
        class: PaP\BackBundle\Command\AnnouncementCommand
        arguments: ["@doctrine_mongodb.odm.default_document_manager"]
        tags:
            -  { name: console.command }

    announcement_form:
            class: PaP\BackBundle\Form\AnnouncementType
            tags:
                - { name: form.type }

    announcement_handler:
        class: PaP\BackBundle\Form\Handler\AnnouncementHandler
        arguments: ["@form.factory", "@request_stack", "@doctrine.orm.entity_manager"]

    notification_handler:
        class: PaP\BackBundle\Notification\Notification
        arguments: ["@form.factory", "@request_stack", "@doctrine.orm.entity_manager"]


