services:
    announcement_handler:
        class: PaP\BackBundle\Form\Handler\AnnouncementHandler
        arguments: ["@form.factory", "@request_stack", "@doctrine.orm.entity_manager"]
        scope: request
        public: true


