language: php

php:
  - 5.5
  - 5.6

sudo: false


env:
  global:
    - MONGODB_VERSION=2.6.10


before_script:
  - sudo pecl install mongo
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - composer install


before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 3


script: phpunit --coverage-text

notifications:
  email:
    - julien@meetserious.com


services:
  - redis-server
  - elasticsearch
  - mongodb
