language: php

php:
  - 5.6

sudo: false

env:
    - SYMFONY_VERSION="2.8.*"

before_install:
  - if [ "$MONGO_VERSION" != "" ]; then pecl -q install -f mongo-2.4.9; fi # Use a specific driver version when needed rather than the one shipped by Travis
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

before_script:
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - composer self-update
  - composer install

script: phpunit -c app

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - julien@meetserious.com


services:
  - redis-server
  - elasticsearch
  - mongodb
