language: php
php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - composer install


script: phpunit --coverage-text

notifications:
  email:
    - julien@meetserious.com

services:
  - redis-server
  - mongodb
  - elasticsearch