language: php
php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - composer install
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=2.6.6 mongodb-org-server=2.6.6 mongodb-org-shell=2.6.6 mongodb-org-mongos=2.6.6 mongodb-org-tools=2.6.6
  - sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - mongo --version


script: phpunit --coverage-text

notifications:
  email:
    - julien@meetserious.com

services:
  - redis-server
  - mongodb
  - elasticsearch