# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # Encoding password
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    # Provide user
    providers:
        in_memory:
            memory:
                users:
                  admin:  { password: %password%, roles: ['ROLE_ADMIN'] }

    # All Firewalls
    firewalls:

        frontoffice:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /back/login_check
                always_use_default_target_path: true
                default_target_path: /back
            logout:
                path: /back/logout
                target: /login
            remember_me:
                secret:   "%secret%"
                lifetime: 804800 # 1 week in seconds
                path:     /back

        backoffice:
            pattern:    ^/back
            security: true
            form_login:
                login_path: /login
                check_path: /back/login_check
                always_use_default_target_path: true
                default_target_path: /back
            logout:
                path: /back/logout
                target: /login
            remember_me:
                secret:   "%secret%"
                lifetime: 804800 # 1 week in seconds
                path:     /back
    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - {path:  ^/back, roles: ROLE_ADMIN}
