<?php

namespace PaP\BackBundle\Repository;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get ALl Announcements by criteria
     * @param string $order
     * @param string $dir
     * @return array
     */
    public function getAllByCriteria($order = "createdAt", $dir ="DESC")
    {
        $query = $this->createQueryBuilder("an")
            ->select( 'an.id','an.title','an.ref','an.price', 'an.photo', 'an.activate')
            ->orderBy("an.{$order}", "{$dir}")
            ->getQuery();

        return $query->getResult();

    }

    /**
     * Get Active Movies
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getActiveAnnouncementBuilder()
    {
        $queryBuilder = $this->getEntityManager()
            ->createQueryBuilder('m')
            ->select('m')
            ->from('Pap\BackBundle\Entity\Announcement', 'm');

        return $queryBuilder;
    }


}
