<?php

namespace PaP\BackBundle\Repository;
use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * NotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsRepository extends DocumentRepository
{

    public function removeOld($interval)
    {
        return $this->createQueryBuilder()
            ->remove()
            ->field('date')->gte(new \DateTime($interval))
            ->getQuery()
            ->execute();
    }

}
